version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t my_image .
      - run:
          name: Testing docker image
          command: docker run --rm -d --name=test -p 8080:8080 my_image && docker ps --last=1 && docker stop test
