version: 2
jobs:
  build:
    environment:
      IMAGE_NAME: gregoiremathian/node-js
    machine:
      - image: ubuntu-2004:202010-01
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:latest .
      - run:
          name: Testing docker image
          command: docker run --rm -d --name=test -p 8080:8080 $IMAGE_NAME:latest && docker ps --last=1 && docker stop test
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PWD" | docker login --username "$DOCKERHUB_USER" --password-stdin
            docker push $IMAGE_NAME:latest