version: 2
jobs:
  build:
    docker:
      - image: node:alpine
    working_directory: /repo
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.21.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
      - run:
          name: Build and Push Docker Image
          command: |
            docker-compose build
            docker-compose push
